[package]
name = "infrazeug-core"
description = "Graph, scheduler, plan/apply, vars, interactor types"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
futures.workspace = true
hex.workspace = true
petgraph.workspace = true
serde.workspace = true
serde_cbor.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
rustc-hash = "2"
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
toml.workspace = true
uuid = { workspace = true, features = ["v5"] }
postcard.workspace = true

infrazeug-emulate = { path = "../infrazeug-emulate" }
infrazeug-secrets = { workspace = true }
infrazeug-native = { workspace = true }
infrazeug-shell = { workspace = true }
rpassword = "7"

[dev-dependencies]
infrazeug-native = { workspace = true }
infrazeug-shell = { workspace = true }
tempfile = "3"
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
divan = "0.1"

[[bench]]
name = "hot_path"
harness = false
