[package]
name = "infrazeug-ext-backblaze-api"
description = "Backblaze B2 Native API client for infrazeug"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
serde = { workspace = true }
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
